version: '3.0'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    hostname: app
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  rasa:
    hostname: rasa
    build: .
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:  
      - run  
      - -m  
      - models   
      - --enable-api  
      - --cors   
      - "*"  